### ISSUE TITLE
needs commons-cli, gnu-crypto, Lua, ...

### ISSUE THREAD

**Issue by daveyostcom** [aerospike/aerospike-sample-applications#2]
Trying to build and run the Java example, I found I needed these things. I downloaded commons-cli, gnu-crypto, and Lua for Mac, but which of the many Lua implementations in Java should I use? What else will I need?

Thanks

**Comment by helipilot50** [comment]
Hi,

The example uses Maven as the project dependency and build tool. Just go to the Java sub directory and enter:

mvn clean package

I hope this helps
